import "./globals.css";
import { latin, Laila } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "@/components/navbar/Navbar";
import Script from "next/script";

const laila = Laila({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata = {
  title: "Best preschool Initiative in Ahmedabad",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={laila.className}>
      <body className={laila.className}>
        <Navbar />
        {children}
      </body>
      <Script src="/js/bootstrap.bundle.min.js" strategy="afterInteractive" />
    </html>
  );
}
