import "./globals.css";
import { latin, Laila } from "next/font/google";

const laila = Laila({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"]
});

export const metadata = {
  title: "Ahmedabad Juniours",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={laila.className}>
      <body className={laila.className}>{children}</body>
    </html>
  );
}
